### PR TITLE
Rkp

### PR DESCRIPTION
**Pull request by AnOddName**
add new header images

### CODE REVIEW

**Comment by emyarod** [comment]
@AnOddName Do we need to keep track of the images in the repo? In any case you just need to replace them in the stylesheet as header1, header2, etc. The max number of headers you can rotate through is 36, so either way some images have to be replaced

**Comment by AnOddName** [comment]
@emyarod I don't necessarily have any affinity for keeping old ones or keeping track of them or whatever. I downloaded all of em so you can do whatever you'd like. I didn't inspect the code too closely but I figured the max was 36.

**Comment by emyarod** [comment]
@AnOddName you can just replace them on the stylesheet in reddit! as long as they are named `header1.png`, `header2.png` and so on. this makes it so that anyone can switch the banner images when we get new ones (if we don't plan on keeping track of them all in the repo anyway, since that will just make the repo grow bigger and bigger as we get new images)

**Comment by AnOddName** [comment]
@emyarod hahah okay I figured, but I didn't want to have them overwrite if you just copied the code over from github incl images

**Comment by emyarod** [comment]
@AnOddName oh nah my placeholders are never comin back

**Pull request closed without merging**
